name: Build-sphinx-docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.5.3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install -r requirements.txt

      - name: Build HTML
        run: |
          cd All_Project_Files/Final_Project_Files/docs/
          make html

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to gh-pages
        run: |
          pip install ghp-import
          ghp-import -n -p -f All_Project_Files/Final_Project_Files/docs/_build/html
